name: Stealing
on: push

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: oven-sh/setup-bun@v1.2.0
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo bun install
    - name: Install browser
      run: sudo bunx playwright install --with-deps chromium
    - name: execute
      run: bun run src/index.ts
