name: Stealing
on:
  schedule:
    - cron: '0,15,30,45 * * * *' # Ejecuta cada hora

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: oven-sh/setup-bun@v1.2.0
    - name: Install dependencies
      run: bun install
    - name: Install browser
      run: bunx playwright install --with-deps chromium
    - name: execute
      run: bun run src/index.ts
