name: Stealing
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: stealing
    env:
        TURSO_URL: ${{ secrets.TURSO_URL }}
        TURSO_TOKEN: ${{ secrets.TURSO_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1.2.0
    - name: Install dependencies
      run: bun install
    - name: Install browser
      run: bunx playwright install --with-deps chromium
    - name: execute
      
      run: bun run src/index.ts
